name: Run Python Script Every 30 Minutes

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download previous data
        uses: actions/download-artifact@v4
        with:
          name: anuncios-data
          path: .
        continue-on-error: true  # No falla si no existe artifact

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          MY_SECRET_PASSWORD: ${{ secrets.MY_SECRET_PASSWORD }}
        run: python bot.py

      - name: Upload updated data
        uses: actions/upload-artifact@v4
        with:
          name: anuncios-data
          path: anuncios_guardados.json
